import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Sparkles, Bot, ArrowRight, Check, RefreshCw, X, FileText, Zap } from 'lucide-react';
import { Form, Question } from '../../types';
import { PRESET_THEMES } from '../../data/presetThemes';

export const AiGeneratorModal: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => {
  const { setActiveFormId, setActiveView, updateForm, showToast } = useApp();
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  if (!isOpen) return null;

  const presetPrompts = [
    'Student CS Course & Instructor Evaluation with 10-point scale',
    'Senior Full Stack Developer Job Application with GitHub & Portfolio',
    'Cyberpunk 2026 Tech Conference Ticket & VIP Workshop RSVP',
    'Customer Product NPS Survey with logic and rating grid'
  ];

  const handleGenerate = () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);

    setTimeout(() => {
      setIsGenerating(false);
      
      const formId = 'form-ai-' + Date.now();
      const generatedForm: Form = {
        id: formId,
        title: prompt.split(' ')[0] ? `${prompt.charAt(0).toUpperCase() + prompt.slice(1)} Form` : 'AI Generated Form',
        description: 'Auto-generated by Gradient AI Form Engine based on prompt: ' + prompt,
        isPublished: false,
        status: 'draft',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        responseCount: 0,
        authorName: 'Gradient AI Agent',
        authorAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
        workspaceId: 'ws-1',
        theme: PRESET_THEMES[1],
        settings: {
          collectEmail: true,
          limitOneResponse: false,
          allowEditResponse: false,
          saveProgress: true,
          showProgressBar: true,
          shuffleQuestions: false,
          quizMode: prompt.toLowerCase().includes('quiz') || prompt.toLowerCase().includes('test'),
          releaseGradeImmediately: true,
          confirmationMessage: 'Your AI form submission has been successfully processed.'
        },
        sections: [
          { id: 'sec-ai-1', title: 'General Information', description: 'Primary details.' },
          { id: 'sec-ai-2', title: 'Specific Feedback & Rating', description: 'In-depth assessment.' }
        ],
        questions: [
          {
            id: 'q-ai-1',
            sectionId: 'sec-ai-1',
            type: 'short_answer',
            title: 'Full Name',
            placeholder: 'Alex Smith',
            required: true
          },
          {
            id: 'q-ai-2',
            sectionId: 'sec-ai-1',
            type: 'email',
            title: 'Contact Email Address',
            placeholder: 'alex@example.com',
            required: true
          },
          {
            id: 'q-ai-3',
            sectionId: 'sec-ai-2',
            type: 'rating',
            title: 'How satisfied are you overall?',
            required: true,
            ratingMax: 5
          },
          {
            id: 'q-ai-4',
            sectionId: 'sec-ai-2',
            type: 'multiple_choice',
            title: 'Which feature did you find most helpful?',
            required: true,
            options: [
              { id: 'o-1', label: 'Speed & UX' },
              { id: 'o-2', label: '3D Interface' },
              { id: 'o-3', label: 'Automated Integrations' }
            ]
          },
          {
            id: 'q-ai-5',
            sectionId: 'sec-ai-2',
            type: 'paragraph',
            title: 'Provide any additional feedback or comments:',
            required: false
          }
        ],
        logicRules: [],
        versions: [{ id: 'v-1', versionNumber: 1, savedAt: new Date().toISOString(), authorName: 'Gradient AI', changesDescription: 'AI Prompt Generation' }]
      };

      // Add generated form to state by calling context helper
      updateForm(formId, generatedForm);
      setActiveFormId(formId);
      setActiveView('builder');
      showToast('AI Form Generated! ✨', 'Form questions, validation, and layout synthesized.', 'success');
      onClose();
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="w-full max-w-xl glass-panel border border-cyan-500/40 rounded-2xl shadow-glow-cyan overflow-hidden relative">
        {/* Header */}
        <div className="p-6 border-b border-white/10 bg-gradient-to-r from-violet-900/30 via-cyan-900/20 to-transparent flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 shadow-glow-cyan">
              <Bot className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-lg font-bold font-display text-white">Gradient AI Form Generator</h3>
              <p className="text-xs text-slate-400">Transform natural language prompt into intelligent forms.</p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Prompt Textarea */}
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-2">
              Describe your form objective:
            </label>
            <textarea
              rows={3}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. Create a CS student lab feedback form with rating scale, instructor evaluation, and code snippet submission..."
              className="w-full p-4 rounded-xl bg-white/5 border border-white/10 text-slate-100 placeholder-slate-500 text-sm focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition-all resize-none"
            />
          </div>

          {/* Preset Chips */}
          <div>
            <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Try Example Prompts:</span>
            <div className="mt-2 flex flex-wrap gap-2">
              {presetPrompts.map((p, idx) => (
                <button
                  key={idx}
                  onClick={() => setPrompt(p)}
                  className="px-3 py-1.5 rounded-lg bg-white/5 hover:bg-cyan-500/10 hover:border-cyan-500/30 border border-white/10 text-xs text-slate-300 transition-colors text-left"
                >
                  <Sparkles className="w-3 h-3 text-cyan-400 inline mr-1.5" />
                  <span>{p}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Generate Button */}
          <div className="pt-4 border-t border-white/10 flex items-center justify-between">
            <span className="text-xs text-slate-400 flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 text-yellow-400" /> Powered by Gradient AI Engine
            </span>

            <button
              onClick={handleGenerate}
              disabled={isGenerating || !prompt.trim()}
              className="flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-cyan-600 via-violet-600 to-magenta-600 hover:from-cyan-500 hover:to-magenta-500 text-white font-bold text-xs shadow-glow-cyan transition-all disabled:opacity-50"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Synthesizing Form Architecture...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>Generate Form</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
